//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaithConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventAttendance
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> eventId { get; set; }
        public Nullable<int> groupId { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
