//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaithConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int id { get; set; }
        public string FeedbackId { get; set; }
        public string UserId { get; set; }
        public string EventId { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
