//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaithConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        public Forum()
        {
            this.ForumComments = new HashSet<ForumComments>();
            this.Media = new HashSet<Media>();
        }
    
        public int id { get; set; }
        public string forumId { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<int> groupId { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual ICollection<ForumComments> ForumComments { get; set; }
        public virtual ICollection<Media> Media { get; set; }
    }
}
