//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaithConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public Groups()
        {
            this.Event = new HashSet<Event>();
            this.Forum = new HashSet<Forum>();
            this.GroupMembership = new HashSet<GroupMembership>();
            this.Post = new HashSet<Post>();
        }
    
        public int id { get; set; }
        public string groupId { get; set; }
        public string groupName { get; set; }
        public string description { get; set; }
        public Nullable<int> groupAdmin { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<Forum> Forum { get; set; }
        public virtual ICollection<GroupMembership> GroupMembership { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual ICollection<Post> Post { get; set; }
    }
}
