//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaithConnect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FaithConnectEntities : DbContext
    {
        public FaithConnectEntities()
            : base("name=FaithConnectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Content> Content { get; set; }
        public DbSet<Event> Event { get; set; }
        public DbSet<EventAttendance> EventAttendance { get; set; }
        public DbSet<Feedback> Feedback { get; set; }
        public DbSet<Forum> Forum { get; set; }
        public DbSet<ForumComments> ForumComments { get; set; }
        public DbSet<GroupMembership> GroupMembership { get; set; }
        public DbSet<Groups> Groups { get; set; }
        public DbSet<Image> Image { get; set; }
        public DbSet<Media> Media { get; set; }
        public DbSet<Post> Post { get; set; }
        public DbSet<PostComments> PostComments { get; set; }
        public DbSet<PostTags> PostTags { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Survey> Survey { get; set; }
        public DbSet<Tags> Tags { get; set; }
        public DbSet<UserAccount> UserAccount { get; set; }
        public DbSet<UserInformation> UserInformation { get; set; }
        public DbSet<vw_Role> vw_Role { get; set; }
    }
}
