//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaithConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Media = new HashSet<Media>();
            this.PostComments = new HashSet<PostComments>();
            this.PostMedia = new HashSet<PostMedia>();
            this.PostTags = new HashSet<PostTags>();
            this.Reaction = new HashSet<Reaction>();
            this.Repost = new HashSet<Repost>();
        }
    
        public int id { get; set; }
        public string postId { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<int> groupId { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual ICollection<Media> Media { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual ICollection<PostComments> PostComments { get; set; }
        public virtual ICollection<PostMedia> PostMedia { get; set; }
        public virtual ICollection<PostTags> PostTags { get; set; }
        public virtual ICollection<Reaction> Reaction { get; set; }
        public virtual ICollection<Repost> Repost { get; set; }
    }
}
