//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaithConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags
    {
        public Tags()
        {
            this.PostTags = new HashSet<PostTags>();
        }
    
        public int Id { get; set; }
        public string tagName { get; set; }
    
        public virtual ICollection<PostTags> PostTags { get; set; }
    }
}
