//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaithConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public UserInformation()
        {
            this.Image = new HashSet<Image>();
        }
    
        public int id { get; set; }
        public string userId { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public Nullable<int> status { get; set; }
        public string bio { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
    
        public virtual ICollection<Image> Image { get; set; }
    }
}
